### ISSUE TITLE
File input example broken?

### ISSUE THREAD

**Issue by RopoMen** [serratus/quaggaJS#66] opened 2015-09-15 18:50 UTC
Hi!
I have tried file input example with Code 128 image saved from here https://en.wikipedia.org/wiki/Code_128

When I'm trying to use that "wikipedia" barcode image with the file input example I cannot get the results.
That "wikipedia" image is working perfectly with LiveStream example (scanned that code from my laptop's screen with my Android.)

Is that example broken?

**Comment by serratus** [comment] 2015-09-16 21:25
Thanks for pointing that out. I could also reproduce this issue of yours, but my examples were still working. So it could only be the __transparency__ problem. Since the image is converted to `PNG` from an `SVG`, the transparency is preserved. Quagga does't like transparency, and I guess any real-world use-case does not have to deal with the 4th color channel, right?

Please add some white spacing and try to re-save it with a white background. If the problem still persists, please attach the image in this issue. Otherwise, please close it. Thanks!

**Comment by RopoMen** [comment] 2015-09-19 09:29
Hi,
Ok, I added some white spacing around it and also changed "inputStream" > "size" to 800 and it worked.

Question to that "size" property, how it actually works? Is it the expected width of the barcode or the image? if it is width of the image, that could be resolved in client side js.

**Comment by serratus** [comment] 2015-09-25 12:57
The `size` property is used to create the internal buffers for processing the image. This was actually implemented to restrict image from being too large. You are right, this restriction could be removed if needed. I'll think about that. Why would you need that?

**Comment by RopoMen** [comment] 2015-09-25 13:13
I was (am) creating a demo page, where I use goratchet and quaggajs and I was going through your examples to setup the live and file reader configurations. I was looking for documentation but that focuses more to barcode detection instead of API interface of the library. (right?)

So my configurations are more or less copy-pasted from your examples. I was able to trace so far that "constraints" is fully related to https://developer.mozilla.org/en-US/docs/Web/API/Navigator/getUserMedia

**Comment by serratus** [comment] 2015-10-15 15:16
You are right, mixing the `size` and `constraints` config properties is a little confusing. The `size` property is only used in case of static images, whereas the `constraints` are defined for live-decoding. Quick example:

### getUserMedia
```javascript
{
  inputStream: { 
    type: "LiveStream",
    constraints: {
      width: 640,
      height: 480,
      facing: "environment"
    },
    area: { // defines rectangle of the detection/localization area
      top: "0%",    // top offset
      right: "0%",  // right offset
      left: "0%",   // left offset
      bottom: "0%"  // bottom offset
    }
  }
}
```

### static images
```javascript
{
  inputStream: {
    size: 640,
    area: { // defines rectangle of the detection/localization area
      top: "0%",    // top offset
      right: "0%",  // right offset
      left: "0%",   // left offset
      bottom: "0%"  // bottom offset
    }
  }
}
```

**Closed** 2015-11-22 20:01 UTC
