### ISSUE TITLE
Support PDF417

### ISSUE THREAD

**Issue by mirodrigom** [serratus/quaggaJS#279] opened 2018-04-04 20:42 UTC
Can we decode PDF417 format barcode scanning support in Quagga JS , because I am using QuaggaJS and other format I want is supported by Quagga and it is the best library I found for barcode decoding. But my essential requirement is PDF417.

Thank you.

**Comment by cvanem** [comment] 2018-04-06 19:01
Mine as well.

**Comment by TomasHubelbauer** [comment] 2018-06-11 12:31
Duplicate of #70.

**Closed by TomasHubelbauer** 2018-06-11 12:31 UTC
