### ISSUE TITLE
Android 6.0 now reads barcodes. What about that?

### ISSUE THREAD

**Issue by yourwebmaker** [serratus/quaggaJS#86] opened 2016-01-07 11:32 UTC
As you probably know, the version 6.0 for Android now reads barcodes natively from camera.

I didn't dig into details but I've installed the latest version on my phone and it worked perfectly.

How can we take the advantage of this feature into quaggaJS?

I found their reader most accurate than ours and perhaps using some native api through web api could be awesome.

**Comment by serratus** [comment] 2016-03-15 21:58
Thanks for pointing out these new capabilities of the native platforms. Now Android and iOS are on-par with this feature. As far as I know iOS supports these feature for some time now. The problem is, that this feature is most probably never going to be exposed to a Web API. That's where Cordova comes into play, but I highly doubt that these features will be part of any browser API.

For sure it would be amazing to get access to this feature through a website and it would be much more efficient and robust to use it that way. But until then we are stuck with all the limitations of the web platform.

**Closed by serratus** 2016-03-15 21:58 UTC
