### ISSUE TITLE
Would like to set length of expected code (for Code 39 VIN detection)

### ISSUE THREAD

**Issue by elsigh** [serratus/quaggaJS#33] opened 2015-05-04 21:09 UTC
It would be cool to say I want a bar code of a particular length for a variable-length encoding to keep the workers working until they decode a value of a particular length.

In my case I'm playing with VINs which use the code_39_reader but a valid VIN is always 17 characters long.

**Comment by serratus** [comment] 2015-05-05 16:25
What you could do is the following: Use the Code39Reader prototype and create a new decoder named VINReader. Then overwrite the decode method and implement a verification step similar to [VINResultParser.java](https://github.com/zxing/zxing/blob/master/core/src/main/java/com/google/zxing/client/result/VINResultParser.java). Then you could only return a result if the barcode is a valid VIN code.

**Comment by elsigh** [comment] 2015-05-05 16:29
That sounds like an awesome idea. Are you into accepting a PR into master for this or should I just do it locally?

**Comment by serratus** [comment] 2015-05-05 16:34
A PR into master would be great. Decoding VIN codes, which are basically Code 39 barcodes, is really specific, but I think many people can benefit from that. Do you have a set of images available for the sake of testing?

**Comment by elsigh** [comment] 2015-05-05 16:42
I only have a couple via Google, and they're old (I expected to find a ton on there but alas). It will be easy for me to procure a handful though. I'll do that now.

**Comment by elsigh** [comment] 2015-05-08 06:27
Would you mind taking a look at my attempt so far? 
My static images example seems to be failing such that I think I might have just done something wrong at a basic level.. 

https://github.com/shiftcars/quaggaJS/commit/bb9a2ca5efc38f55a172b0fc429e4b639cd92f79

**Comment by elsigh** [comment] 2015-05-10 05:16
I also tried just replacing the code_39 images and I set the default state to have numOfWorkers:0 (so my breakpoints would work) and debug: true as well as a number of other options that looked debugging related in config.js but none of those seemed to change much.

Also, I tried inferring what the right config should be based on the names of the vars but maybe I guessed wrong? Since I wasn't getting much in the way of results I set halfPatch: false (thinking that means it will try with a higher resolution version of the patch). I set patch: large (I dunno, code39 VINs look long). Some documentation about config.js would be awesome - did I miss it somewhere?

My patch has a bunch of VIN images that mostly work pretty quickly with a native scanner (and a few of them don't) - so I think it's a reasonable set of test fixtures. The first image should work but the only one that does for me is image-006.jpg. 

Hopefully the image set might be helpful to you too?

**Comment by elsigh** [comment] 2015-05-10 05:31
Ha! Having just written that, I think that the aspectRatio might really help me - in Landscape mode. I have it implemented on my side, and if I set the minAspectRatio and maxAspectRatio to 4 I get a horizontally oriented video scanner and it is able to focus and get a higher resolution with less pixels to deal with. I can now decode the first image in my set consistently (on a device in Landscape mode)

**Comment by serratus** [comment] 2015-05-11 19:04
Yeah, the documentation is still rather sparse and lacks of details for people who want to contribute. Thanks for adding the constraints for ``minAspectRatio`` and ``maxAspectRatio``. This should help quite a bit, just simply because less noise is distracting the reader from the actual barcode. Well done!

**Comment by elsigh** [comment] 2015-05-11 19:10
I'll put up a demo app I've made soon with this - for Android, Chrome now has Add-to-Homescreen and with that you can specify orientation mode for your "app" in that context, meaning I can use minAspectRatio:5/maxAspectRatio:5 and get a landscape horizontal bar that works quite well for the VIN barcode!

**Comment by serratus** [comment] 2015-05-11 19:30
Sounds great! I just noticed those ``aspectRatio`` constraints are currently only working in Chrome, right? When I try your [link](https://src.chromium.org/svn/trunk/src/chrome/test/data/webrtc/manual/constraints.html) and fiddle with the ``aspectRatio`` the video stays dark.

**Comment by elsigh** [comment] 2015-05-11 19:35
On Mon, May 11, 2015 at 12:30 PM, Christoph Oberhofer <
notifications@github.com> wrote:

> Sounds great! I just noticed those aspectRatio constraints are currently
> only working in Chrome, right? When I try your link
> <https://src.chromium.org/svn/trunk/src/chrome/test/data/webrtc/manual/constraints.html>
> and fiddle with the aspectRatio the video stays dark.
>
That may very well be. I didn't test anything other than Chrome.

**Comment by serratus** [comment] 2015-05-11 19:36
I just figured out why you are having problems with the static images. The image dimensions are all really odd (e.g.: 401 x 234) and therefore no grid can be calculated. This can easily be fixed by setting a size to the ``inputStream``´like so:

````javascript
inputStream: {
    name: "Test",
    type: "ImageStream",
    src: "../test/fixtures/code_39_vin/",
    length: 10,
    size: 640 // setting the size of the wide side
},
````

**Comment by serratus** [comment] 2015-05-11 19:42
It will still fail, because all the images have different dimensions. I'll normalize them. The ``ImageStream`` can only work with images of the same size, since it's initial implementation was intended to replace the ``<video>`` element with images extracted from a video to achieve deterministic results every time.

**Comment by elsigh** [comment] 2015-05-11 19:43
Ah! That makes sense really. OK, I can do that in this change too, no big
deal - I'm addressing your other comments and will push to my branch again
here within the hour

**Comment by elsigh** [comment] 2015-05-11 19:47
Maybe I'll push the code changes first and then fix the images later - that
will take time and getting the code merges is more of a priority to me -
cool?

**Comment by serratus** [comment] 2015-05-11 19:48
Sounds great!

**Closed** 2015-05-12 17:52 UTC
Labels: enhancement

**Comment by jamsshhayd** [comment] 2017-10-31 21:56
Were you able to read the VIN numbers correctly? In my case it all messes up even in the fileupload mode. Other Barcode types are being scanned perfectly fine.
Please do share the sample code if you had this issue fixed.
