### ISSUE TITLE
Code39 seems to be wrong (adds an extra I in the beginning)

### ISSUE THREAD

**Issue by elsigh** [serratus/quaggaJS#31] opened 2015-05-04 17:52 UTC
I'm tinkering with VIN decoding and here's one example:
http://d5799487.zz840.hamshawdesign.net/wp-content/uploads/2013/03/vin.jpg

I tried a couple that worked and in both cases there was an extra upper-cased I as the first character. code.slice(1) gives me the correct VIN. Not sure what's up as I haven't looked much at the actual code there.

**Comment by serratus** [comment] 2015-05-05 16:20
As far as I have noticed, decoding is not the issue. If you look closely, and compare the first digit after the start pattern to the pattern defined in [wikipedia](http://en.wikipedia.org/wiki/Code_39#/media/File:Free_3_of_9_%28Code_39_barcode%29.svg) it really is a upper-cased I.

If you want to work with VINs, you have to verify the code anyway. Take a look at [VINResultParser.java](https://github.com/zxing/zxing/blob/master/core/src/main/java/com/google/zxing/client/result/VINResultParser.java) in the zxing repository. They just strip the characters (I, O and Q) which are not allowed in the VIN. Hope that helps.

In my opinion, this is not a bug. Please verify so I can close this issue.

**Comment by elsigh** [comment] 2015-05-05 16:30
Cool, I agree - you should close this and I should implement a VINDecoder that does any normalization, as you suggested in the other issue I filed. Thanks for the prompt replies!

**Comment by serratus** [comment] 2015-05-05 16:48
Happy to help!

**Closed by serratus** 2015-05-05 16:48 UTC
